device: "cuda"
sample_rate: 4096
hoft_dir: "/home/muhammed.saleem/deepClean/deepcleanv2/data_replay/tests/H1/llhoft"
witness_dir: "/home/muhammed.saleem/deepClean/deepcleanv2/data_replay/tests/H1/lldetchar"
outdir: '../../myprojects/60Hz-O3-MDC/cleaned_frames'
train_dir: "../../myprojects/60Hz-O3-MDC/results/lightning_logs/version_8/"
